name: On push, deploying to Test
on: [push]
jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-build-deploy.yml@main
    with:
      process_env: Test
    secrets: inherit

  build-docker-image:
    uses: octopusden/octopus-oc-srv-jobs-ldap-user-locker/.github/workflows/common-docker-build-deploy.yml@8-add-docker-image-release-actions
    with:
      build-args: |
        DOCKER_REGISTRY_HOST=ghcr.io
        PYTHON_VERSION=3.7
      tags: |
        ghcr.io/${{ github.repository }}:${{ github.ref_name }}
