name: On push, deploying to Test
on: [push]
jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-build-deploy.yml@main
    with:
      process_env: Test
    secrets: inherit

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: List Current Directory
        run: ls -1N --color=never
      - name: Build Docker Imate
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          build-args: |
            DOCKER_REGISTRY_HOST="ghcr.io"
            PYTHON_VERSION="3.7"

