name: On push, deploying to Test

inputs:
  docker_registry_host:
    description: Docker registry host to push image to
    required: false
    type: string
    default: ghcr.io

on: [push]

jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-build-deploy.yml@main
    with:
      process_env: Test
    secrets: inherit

  build-push-docker-image:
    uses: octopusden/octopus-base/.github/workflows/common-docker-build-deploy.yml@main
    with:
      build-args: |
        PYTHON_VERSION=3.7
      tags: |
        ${{ inputs.DOCKER_REGISTRY_HOST }}/${{ github.repository }}:${{ github.ref_name }}
